#!/usr/bin/env bash
#This Bash script pings an IP address passed as an argument
#Accepts a string as an argument
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#Pings the IP 5 times

if [ -z "$1" ]; then
   echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
elif [ "$#" -gt 1 ]; then
   echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
   exit
else 
    ping "$1" -c 5
fi
