#!/usr/bin/env bash
#This Bash script displays To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

var1='To infinity and beyond'
trap "echo 'I am invincible!!!'" SIGTERM
while true
do
    echo "$var1"
    sleep 2
done
