#!/usr/bin/env bash
#This Bash script displays numbers from 1 to 100 and
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format

var='FizzBuzz'
var1='Fizz'
var2='Buzz'
i='1'
while [ $i -le 100 ]
do
  if (( i % 3 == 0 && i % 5 == 0)); then
     echo "$var"
  elif (( i % 3 == 0 )); then
      echo "$var1"
  elif (( i % 5 == 0 )); then
      echo "$var2"
  else
     echo "$i"
  fi
  (( i++ ))
done
