#!/usr/bin/env bash
# using apache to run on a docker container and returning a page
# containing Hello ALX when querying the root of it

sudo apt-get update
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello ALX" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
